name: mobil_bmw
description: "A new Flutter project. This is a project to display a list of BMW cars."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_rating_bar: ^4.0.1 # <-- BAGIAN INI YANG DITAMBAHKAN

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/7series.png
    - assets/images/i4.png
    - assets/images/ix.png
    - assets/images/logo.png
    - assets/images/m3.png
    - assets/images/x5.png
    - assets/images/z4.png